### ISSUE TITLE
Zabbix 5 import error

### ISSUE THREAD

**Issue by Lamar463** [Art3mK/Zabbix-LSI-RAID-Monitoring#11]
Hi !

When try to import template in my zabbix 5 server its said

```
Import failed

    Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 68 | Column: 89].
```

Is it real to use this template with zabbix 5 ?

**Comment by Art3mK** [comment]
Hey,

did you get it working?

**Comment by Lamar463** [comment]
> 
> 
> Hey,
> 
> did you get it working?

Oh, sorry. I just noticed that I downloaded the template incorrectly.
